version: '3'
services:
  node:
    build: ./docker/node
    image: node
    container_name: node
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./test:/home/radee2019
  python:
    build: ./docker/python
    image: python
    container_name: python
    tty: true
    ports:
      - 5555:5555
      - 8000:8000
      - 8888:8888
    volumes:
      - ./test:/home/radee2019
